### ISSUE TITLE
PNGs with transparency have a black background after compression

### ISSUE THREAD

**Issue by NicolaSaunders** [saroamirkhanyan/compress-images-tool#1]
I tested your package with a PNG downloaded from https://www.freepngs.com/cat-pngs. The reduction in file size is excellent, but the transparent areas of the PNG have a solid black background instead, making it unusable.

**Comment by saroamirkhanyan** [comment]
Hi, thanks for your feedback, I will solve that problem

**Comment by saroamirkhanyan** [comment]
I have solved this problem, so I am closing this issue

**Comment by NicolaSaunders** [comment]
Perfect - thanks a lot!!
